apiVersion: v1
kind: Secret
metadata:
  name: vmanage-credentials
  namespace: awi-system
type: Opaque
data:
  # Provide base64 encoded username
  # and password.
  username: "{VMANAGE_USERNAME}"
  password: "{VMANAGE_PASSWORD}"

---

apiVersion: v1
kind: Secret
metadata:
  name: gcp-credentials
  namespace: awi-system
type: Opaque
data:
  # Provide base64 encoded content of file
  # with the GCP Credentials to your service
  # account.
  gcp-key.json: "{GCP_CREDS}"

---

apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
  namespace: awi-system
type: Opaque
data:
  # Provide base64 encoded content of the
  # aws credentials file with your account
  # credentials.
  credentials: "{AWS_CREDS}"

---

apiVersion: v1
kind: Secret
metadata:
  name: kube-config
  namespace: awi-system
type: Opaque
data:
  # Provide base64 encoded content of the
  # file with your k8s context and its
  # credentials.
  config: "{K8S_CTX}"
